### ISSUE TITLE
Question: FAN_MAX & MIN_TEMP <-> OFF_TEMP

### ISSUE THREAD

**Issue by EagleeyeKai** [DriftKingTW/Raspberry-Pi-PWM-Fan-Control#12]
Hi there,

why is the constant FAN_MAX to be defined? It is not used in the code or do I miss something?

I have anther question regarding the MIN_TMEP and OFF_TEMP. What is the reason to define the OFF_TEMP constant? There is no case made if the temperature is between OFF_TEMP and MIN_TEMP which is 40 / 45 at default. Wouldnt it make sense to not use OO_TEMP and just stop the fan if the temp is below MIN_TEMP?

Thanks and best regards
Kai

**Comment by DriftKingTW** [comment]
Hi Kai,

1. `FAN_MAX` is originally design to turn on the fan fully when temperature reaches `MAX_TEMP`, it's not necessary if the `FAN_HIGH` sets to `100`. We leave it there as an option that you can modify it to fit in different use case.

2. `MIN_TMEP` and `OFF_TEMP` is for debouncing purpose. If you cut the fan off immediately when reaches `MIN_TEMP`, CPU temperature is very likely to go up again. Causing the fan to keep turning on and off. We need to make sure the CPU is cool enough to not to restart the fan in very short time.

Best,
DriftKingTW
