### ISSUE TITLE
Script eats a lot of CPU

### ISSUE THREAD

**Issue by Zappelphilipp** [DriftKingTW/Raspberry-Pi-PWM-Fan-Control#8]
not sure why, but running this script with python2 oder python3 shows me about 13%-21% CPU ussage in htop no matter what refreshrate i configure. 

can someone confirm this bug?

**Comment by DriftKingTW** [comment]
Hi, I've found this issue is caused by the PWM frequency, the library uses kHz not Hz.
Already fix in the latest commit, thanks for point it out.
